
" Use powerline, the ultimate statusline/prompt utility
set rtp+=/usr/lib/python2.7/site-packages/powerline/bindings/vim


set laststatus=2
set encoding=utf-8

" Set filetype detection on, load plugins and indent.
filetype plugin indent on

set nocompatible
syntax on
set t_Co=256
"colorscheme ir_black
colorscheme zenburn
colorscheme molokai
"colorscheme wombat
"set background=dark

set tabstop=4       " The width of a TAB is set to 4.
                    " Still it is a \t. It is just that
                    " Vim will interpret it to be having
                    " a width of 4.

set shiftwidth=4    " Indents will have a width of 4

set softtabstop=4   " Sets the number of columns for a TAB

set expandtab       " Expand TABs to spaces


" Various.
set bs=2 " Backspace, this is the same as :set backspace=indent,eol,start.
"set ruler " Show the cursor position.
"set scrolloff=5 " Show 5 lines above/below the cursor when scrolling.
set number " Line numbers on.
"set showcmd " Shows the command in the last line of the screen.
set autoread " Read files when they've been changed outside of Vim.
"set cursorline " Highlight current line, I found this slowed things.

" Bells and whistles.
set novisualbell
set noerrorbells
"set t_vb=

set history=300 " Number of command lines stored in the history tables.

set title " Set the title in the console.

" Use matchtime and showmatch together.
set matchtime=2 " Time to show matching parent in 10ths of a sec.
set showmatch " Show matching parents.

" Backup.
set nobackup " Don't backup files.
set nowritebackup
set noswapfile

" Searching.
set hlsearch
"set incsearch
set ignorecase
set smartcase

set wildmode=longest,list " File and directory matching mode.


" Diff opt
set diffopt=vertical

" Drupal command group, set the correct filetypes for Drupal files.
augroup drupal
  autocmd BufRead,BufNewFile *.module set filetype=php
  autocmd BufRead,BufNewFile *.theme set filetype=php
  autocmd BufRead,BufNewFile *.inc set filetype=php
  autocmd BufRead,BufNewFile *.install set filetype=php
  autocmd BufRead,BufNewFile *.info set filetype=php
  autocmd BufRead,BufNewFile *.profile set filetype=php
  autocmd BufRead,BufNewFile *.test set filetype=php
augroup END

" Prevent help popping up catch <F1> instead of <ESC>.
:nmap <F1> <ESC>
:map <F1> <ESC>
:imap <F1> <ESC>

" Map keys to navigate tabs
:map <C-Left> :tabprevious<CR>
:map <C-Right> :tabnext<CR>

" When editing a file, always jump to the last cursor position.
set viminfo='10,\"100,:20,%,n~.vim/viminfo
function! ResCur()
  if line("'\"") <= line("$")
    normal! g`"
    return 1
  endif
endfunction

augroup resCur
  autocmd!
  autocmd BufWinEnter * call ResCur()
augroup END
